### ISSUE TITLE
Remove `pushd` and `popd` from install instructions

### ISSUE THREAD

**Issue by riazarbi** [crazycapivara/h3-r#19]
These install instructions - 

```
git clone https://github.com/crazycapivara/h3-r.git
pushd h3-r
chmod +x install-h3c.sh
# Install H3 C Library
./install-h3c.sh
# Install H3 for R
R -q -e 'devtools::install()'
popd
rm -rf h3-r
```
work when installing manually in bash or when running in a bash script. 

However, they do not work when adding them to a Dockerfile. A workaround is to put the commands in a bash script, copy the bash script into the container on `docker build...` and then `RUN bash script.sh`. But this adds an unnecessary bash script to a docker build. 

Suggest you replace `pushd` and `popd` with another method so that these commands can be put in a Dockerfile. I experimented with replacing `pushd` with `cd` but couldn't get the package to build. 

Currently using the `bash script.sh` method in by `docker build...` but it would be great if I could eliminate it.

**Comment by crazycapivara** [comment]
Your are right.

In your case when using `cd` I think it did not build because you have to run `install-h3c.sh` with `bash` as well.

Please see the [Dockerfile](https://github.com/crazycapivara/h3-r/blob/master/Dockerfile) I have added to run `h3` with optional `sf` package in an _RStudio_ container.

**Comment by riazarbi** [comment]
I used the same commands as you did in your Dockerfile and it all works fine. Thank you. 

```
RUN git clone https://github.com/crazycapivara/h3-r.git \
    && cd h3-r \
    && chmod +x install-h3c.sh \
    && bash ./install-h3c.sh \
    && R -q -e 'devtools::install()' \
    && cd .. \
    && rm -rf h3-r
```
