### ISSUE TITLE
Request: Polyfill

### ISSUE THREAD

**Issue by riazarbi** [crazycapivara/h3-r#28]
Hello,

I have moved from using `h3forr` to `h3-r` in most of my projects (it's much faster!).

Recently I had to go over some legacy code, and realized that h30r does not have a `polyfill` function. 

Could it be added? Then I could use `h3-r` instead of `h3forr`. (Unless I find another one of course!)

**Comment by crazycapivara** [comment]
Hi, yeah it's plan to be added. Hope I can do it soon.

**Comment by crazycapivara** [comment]
@riazarbi Just added the `polyfill` function in #29. Please install from branch `feature/polyfill` and check, if it fits for your legacy code.

**Comment by riazarbi** [comment]
I refactored the legacy code with a non-polyfill workaround, unfortunately. 

But I did rebuild our docker images with the `feature/polyfill` branch and run your sample code and it all runs fine. 

Thanks for this, it'll be used quite soon as there is work that has been waiting for it.
