### ISSUE TITLE
Possible issue with h3::polyfill on multipolygons

### ISSUE THREAD

**Issue by hdrs** [crazycapivara/h3-r#42]
I have been using h3::polyfill on some varied shapes and sometimes I get weird results on multipolygons.   I do not know if this is the R code interface or the underlying h3 library.  I am using sf:: tools within R. 

I have a sample hosted for testing but have found numerous further examples. 

`item <- sf::st_read("https://gist.githubusercontent.com/hdrs/f273f2820d40d45f8ecda49840bec521/raw/9fdebbaefcb811b9c554a18e73e47d69abb8a54b/map.geojson")`

This is a 4 polygon multipolygon. There are no holes. The components all obey the RH rule.  The multipolygon and the components individually all test as valid with sf::st_is_valid(). 

`h3ids <- h3::polyfill(item, res=10)`
`h3geom <- h3::h3_to_geo_boundary_sf(h3ids)`

Here is a plot of what those h3 tiles look like

![polyfill_issue_01](https://user-images.githubusercontent.com/20231698/133149299-27ce5e2d-7047-40ac-a737-e3f3ae73bfa7.png)

For reference, here is the result when I break apart the multipolygon with  sf::st_cast(item, "POLYGON") and run h3::polyfill on each component. This plot seems correct. 

![polyfill_issue_02](https://user-images.githubusercontent.com/20231698/133149435-66158f61-fb64-4415-a48d-232d82f755c2.png)

Note, this also happens with a single polygon with multiple holes. I can update this with an example of that if it seems useful.

**Comment by crazycapivara** [comment]
@hdrs Yes, you are right multipolygons are not supported yet. I have to implement an R function to cast the multipolygon, so that it will be accepted by h3. This is more or less what you already did, splitting up to single polygons and looping over them.
Nevertheless, holes should be accepted as mentioned in the [h3js](https://github.com/uber/h3-js#module_h3.polyfill) API reference.
Can you post an 'hole' example?

**Comment by hdrs** [comment]
Here is an example with multiple holes hosted as a gist. 

`item <- sf::st_read("https://gist.githubusercontent.com/hdrs/34eb2042bacce0eee58dbe08fbcc8af8/raw/494b6c914443540a459088ed8d26e34732661967/map.geojson")`

It checks out as valid according to sf.

`sf::st_is_valid(item)`

I run this to find the h3 tiles

`h3ids <- h3::polyfill(item, res=7)`
`h3geom <- h3::h3_to_geo_boundary_sf(h3ids)`

That gives the following result.

![polyfill_issue_04](https://user-images.githubusercontent.com/20231698/133608249-01ec31c6-bd97-438a-80d5-9d6d7d8798e8.png)
